version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: your-db
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8443:8443"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  metabase:
    image: metabase/metabase:latest
    restart: always
    container_name: metabase
    hostname: metabase
    environment:
      JAVA_OPTS: -Xmx2g
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./fs/volumes/metabase/plugins:/plugins
    depends_on:
      - clickhouse
  